### ISSUE TITLE
Unification of Coupons flow

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#240]
Implement the recommendation by Vikas to ensure consistency of coupons workflow. 

![Image](https://github.com/user-attachments/assets/7f3a491b-a7bf-4743-8781-c569799172e3)
[User Experience - Coupons and Bookings v1.1 (1).pdf](https://github.com/user-attachments/files/19647760/User.Experience.-.Coupons.and.Bookings.v1.1.1.pdf)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych all the issues presented below were addressed, and ready for test.
![Image](https://github.com/user-attachments/assets/a9806207-1646-4e6f-9467-09ff9d2a5565)

**Comment by Gaskevych** [comment]
Dear @MiriamObibi just flagging for your attention when you have time. Thank you!

**Comment by Gaskevych** [comment]
@MiriamObibi can you please kindly have a look at this one? We seem to be facing some challenges with the flow for Poland so just want to make sure that Vikas's recommendations have been addressed. Thanks!

**Comment by MiriamObibi** [comment]
Thanks for the reminder @Gaskevych . See my observations below
1. If client chooses Provider first, the information  on what a coupon is, is still not displayed. Not fixed
2. Could not find the feature requesting for the removal of coupon code, appears fixed.
3. Coupon code not seen when changing time and date, after selecting the new time and date and clicking 'save', there was a black hanging screen. Had to force the app to close on 3 instances, same result. Not fixed
4. Manual selection of each day is still required, No change effected. 
For clarity and if you dont mind,  (@sebastian-7DIGIT could you please highlight what was done from your end for each of the issues?

**Comment by Gaskevych** [comment]
Dear @MiriamObibi can you please have a look? Should we close it now?

**Comment by MiriamObibi** [comment]
All good. Thanks
